# Generated by Django 4.2.24 on 2025-09-14 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sanguine', '0002_mood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Select the date for this mood'),
        ),
    ]
