# Generated by Django 4.2.24 on 2025-09-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanguine', '0003_mood_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='mood_type',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('calm', 'Calm')], default='happy', help_text='Select your current mood', max_length=20),
        ),
    ]
