# Generated by Django 4.2.24 on 2025-09-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanguine', '0004_mood_mood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='age',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='breed',
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood_type',
            field=models.CharField(choices=[('depressed', 'Depressed'), ('sad', 'Sad'), ('okay', 'Okay'), ('good', 'Good'), ('happy', 'Happy'), ('ecstatic', 'Ecstatic'), ('irritated', 'Irritated'), ('mad', 'Mad')], default='happy', help_text='Select your current mood', max_length=20),
        ),
        migrations.AlterField(
            model_name='mood',
            name='name',
            field=models.CharField(default='My Mood', max_length=100),
        ),
    ]
