# Generated by Django 5.2.6 on 2025-09-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanguine', '0005_remove_mood_age_remove_mood_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='custom_text',
            field=models.CharField(blank=True, help_text='Custom text to display instead of mood image', max_length=200, null=True),
        ),
    ]
