# Generated by Django 5.2.6 on 2025-09-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanguine', '0006_mood_custom_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='custom_text',
        ),
    ]
