# Generated by Django 5.2.6 on 2025-09-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanguine', '0007_remove_mood_custom_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood_type',
            field=models.CharField(choices=[('depressed', 'Depressed'), ('sad', 'Sad'), ('okay', 'Okay'), ('good', 'Good'), ('happy', 'Happy'), ('ecstatic', 'Ecstatic'), ('irritated', 'Irritated'), ('mad', 'Mad'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('calm', 'Calm'), ('confused', 'Confused'), ('grateful', 'Grateful'), ('lonely', 'Lonely'), ('content', 'Content'), ('overwhelmed', 'Overwhelmed'), ('peaceful', 'Peaceful'), ('energetic', 'Energetic'), ('bored', 'Bored'), ('proud', 'Proud')], default='happy', help_text='Select your current mood', max_length=20),
        ),
    ]
